Gst alsa start at
CreatorDev/packages pull request #6
Opened 2016-11-29 09:09 UTC by abhilashtuse

Maintainer: me / @<github-user>
Compile tested: MIPS, Creator Ci40 (https://github.com/CreatorDev/openwrt)
Run tested: Tested with a clean build

Description:
Alsa start-at facilitates starting a playback stream at a specified absolute time, which can be used to achieve synchronized playback.

2016-11-30 17:35 UTC, Ham22 requested changes

2016-11-30 17:35 UTC, Ham22 commented on multimedia/gst1-plugins-base/patches/004-Synchronize-playback-support-using-alsa-start-at.patch
> +Signed-off-by: Abhilash Tuse <Abhilash.Tuse@imgtec.com>
A bit of a description of what the patch does would be useful here. Same for the alsa patch too.

Also, some developers put significant effort into this, perhaps mention some of the key players in signed off by.

2016-12-02 06:32 UTC, MJNowakowski requested changes

2016-12-02 06:32 UTC, MarcinNowakowski-IMG commented on multimedia/gst1-plugins-base/patches/004-Synchronize-playback-support-using-alsa-start-at.patch
> ++2016-11-22  gettextize  <bug-gnu-gettext@gnu.org>
gettextize update has nothing to do with with adding playback support, so why is it added in this patch file?

2016-12-02 06:32 UTC, MarcinNowakowski-IMG commented on multimedia/gst1-plugins-base/patches/004-Synchronize-playback-support-using-alsa-start-at.patch
> +Signed-off-by: Marcin Nowakowski <marcin.nowakowski@imgtec.com>
AFAIR there was no work done by me here except for the gettext version update, which must not be part of this patch.

2016-12-22 07:04 UTC, closed without merging